import Footer from '@/components/footer/Footer'
import {getPostList} from '@/components/header/graphql/useGetPostListQuery'
import Header from '@/components/header/Header'
import {getClient} from '@/components/lib/ApolloClient'
import type {Metadata} from 'next'
import {ApolloWrapper} from './components/lib/ApolloWrapper'
import {getSocialMedia} from './components/social_media_links/graphql/useGetSocialMediaQuery'
import './globals.css'
import './reset.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const {data: postData, error: postError} = await getClient().query({
        query: getPostList,
    })
    const {data: socialMediaData, error: socialMediaError} =
        await getClient().query({
            query: getSocialMedia,
        })
    if (postError || socialMediaError) return <p>Error Loading this Element</p>
    if (
        !postData ||
        !postData.posts ||
        !socialMediaData ||
        !socialMediaData?.socialMediaLinks
    ) {
        return <p>Element Fail to Load</p>
    }

    return (
        <html lang='en'>
            <body>
                <ApolloWrapper>
                    <Header headerMenuOptions={postData} />
                    {children}
                    <Footer socialMediaInfo={socialMediaData} />
                </ApolloWrapper>
            </body>
        </html>
    )
}
